# Generated by Django 3.1.7 on 2022-05-17 13:38

from django.db import migrations, models
import socialmedia.validators


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediamodel',
            name='category_content',
            field=models.CharField(choices=[('programming', 'Programming'), ('vlog', 'Vlog'), ('culinary', 'Culinary'), ('nan', 'Not Set')], default='nan', max_length=50),
        ),
        migrations.AlterField(
            model_name='socialmediamodel',
            name='first_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='socialmediamodel',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='socialmediamodel',
            name='username',
            field=models.CharField(max_length=50, validators=[socialmedia.validators.validasi_username]),
        ),
    ]
