# Generated by Django 3.1.7 on 2022-05-15 05:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20220515_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='waktu_postingan',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
