# Generated by Django 3.1.7 on 2022-05-24 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artikel',
            old_name='slug_artikel',
            new_name='slug',
        ),
    ]
