# Generated by Django 3.1.7 on 2022-08-25 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artikel',
            options={'default_permissions': ('add', 'change', 'delete'), 'permissions': (('publish_artikel', 'Can publish artikel'),)},
        ),
    ]
