# Generated by Django 3.1.7 on 2022-05-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artikel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_artikel', models.CharField(max_length=233)),
                ('isi_artikel', models.TextField(max_length=800)),
                ('penulis_artikel', models.CharField(max_length=100)),
                ('publish_artikel', models.DateTimeField(auto_now_add=True)),
                ('update_time_artikel', models.DateTimeField(auto_now=True)),
                ('slug_artikel', models.SlugField(blank=True, editable=False)),
            ],
        ),
    ]
